version: "2.2"

services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000
      - 15432:15432
    environment:
      - CUBEJS_DEV_MODE=true
    volumes:
      - .:/cube/conf

  backend:
    image: python:3.11
    working_dir: /backend/server
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend/server
    command: >
      bash -c "pip install -r requirements.txt  && uvicorn server:app --host 0.0.0.0 --port 8000"

  frontend:
    image: node:20.5.1
    working_dir: /frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
    command: >
      bash -c "npm install && npm start"
